usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqicns.so
usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqmng.so
usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqtga.so
usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqtiff.so
usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqwbmp.so
usr/lib/${DEB_HOST_MULTIARCH}/qt6/plugins/imageformats/libqwebp.so
